Update calculator_pipeline.yml

diff --git a/.github/workflows/calculator_pipeline.yml b/.github/workflows/calculator_pipeline.yml
--- a/.github/workflows/calculator_pipeline.yml
+++ b/.github/workflows/calculator_pipeline.yml
@@ -28,9 +28,9 @@ jobs:
         run: |
           pip install -r BE/requirements.txt
 
-      - name: Start the REST API
-        run: |
-          python BE/calculator.py --rest &
+      # - name: Start the REST API
+      #   run: |
+      #     python BE/calculator.py --rest &
 
       - name: Start Selenium
         run: docker run --name selenium -d --add-host host.docker.internal:host-gateway -p 4444:4444 -p 5900:5900 --shm-size="2g" selenium/standalone-chrome:4.2.1-20220531
@@ -38,17 +38,17 @@ jobs:
       - name: Start Calculator Front end docker
         run: docker compose -p webcalculator up -d
     
-      - name: Run Unit and API tests
-        run: |
-          export PYTHONPATH=.
-          pytest tests/ --junit-xml=report.xml
+      # - name: Run Unit and API tests
+      #   run: |
+      #     export PYTHONPATH=.
+      #     pytest tests/ --junit-xml=report.xml
 
-      - name: Upload test results
-        uses: mikepenz/action-junit-report@v4  
-        if: success() || failure()
-        with:
-          report_paths: '**/report.xml'
-          require_tests: true 
+      # - name: Upload test results
+      #   uses: mikepenz/action-junit-report@v4  
+      #   if: success() || failure()
+      #   with:
+      #     report_paths: '**/report.xml'
+      #     require_tests: true 
 
       - name: Log in to Azure Container Registry
         uses: docker/login-action@v3
